// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoDNQI6sPRgnM0ACS2eXNcXliTwZGMyEc',
    appId: '1:648302226592:web:a7b561c9a44a69d83eadc5',
    messagingSenderId: '648302226592',
    projectId: 'chat-app-6eda4',
    authDomain: 'chat-app-6eda4.firebaseapp.com',
    storageBucket: 'chat-app-6eda4.firebasestorage.app',
    measurementId: 'G-DLWHF1FJM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj0OcL93ZFPygLn6L0pe32wsbX2IL-7xA',
    appId: '1:648302226592:android:30c356b1d421d8b43eadc5',
    messagingSenderId: '648302226592',
    projectId: 'chat-app-6eda4',
    storageBucket: 'chat-app-6eda4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM6wNHp28tmmrQE-Ao9OtYK91M3rDQZO0',
    appId: '1:648302226592:ios:14ce4726636168dd3eadc5',
    messagingSenderId: '648302226592',
    projectId: 'chat-app-6eda4',
    storageBucket: 'chat-app-6eda4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM6wNHp28tmmrQE-Ao9OtYK91M3rDQZO0',
    appId: '1:648302226592:ios:14ce4726636168dd3eadc5',
    messagingSenderId: '648302226592',
    projectId: 'chat-app-6eda4',
    storageBucket: 'chat-app-6eda4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoDNQI6sPRgnM0ACS2eXNcXliTwZGMyEc',
    appId: '1:648302226592:web:29c15b2bceb3bb223eadc5',
    messagingSenderId: '648302226592',
    projectId: 'chat-app-6eda4',
    authDomain: 'chat-app-6eda4.firebaseapp.com',
    storageBucket: 'chat-app-6eda4.firebasestorage.app',
    measurementId: 'G-9VKCX60SFH',
  );
}
